dir_source: "datasets/complete_datasets_csv"
dir_output: "datasets/complete_datasets_csv_processed_5m_zstd(gen)_dbscan(daily)"

remove_duplicates: true
remove_wrong_dates: true
remove_points_outside_polygon: true

split_continuous_segments: true
gap_threshold: "10m"

normalize: false
norm_mode: "z-standardization"
norm_daily_based: false
norm_cols: ["latitude", "longitude", "wind_speed", "wind_direction", "u_component", "v_component"]

remove_outliers: true
outlier_mode: "dbscan"
outlier_daily_based: true
outlier_cols: ["u_component", "v_component"]

sliding_window: true
window_size: "5m"

daily_based: false
